language: ruby
rvm:
  - 2.6.3
env:
  - "RAILS_VERSION=6.0.0.rc1"
matrix:
  exclude:
    - rvm: 2.0.0
      env: "RAILS_VERSION=5.0.0"
    - rvm: 2.1.0
      env: "RAILS_VERSION=5.0.0"
    - rvm: 2.1.5
      env: "RAILS_VERSION=5.0.0"
    - rvm: 2.2.0
      env: "RAILS_VERSION=5.0.0"
    - rvm: 2.2.1
      env: "RAILS_VERSION=5.0.0"
    - rvm: 2.4.0
      env: "RAILS_VERSION=4.2.0"

notifications:
  email:
    recipients:
      - j@srv.im
    on_success: change
    on_failure: change
